### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mdsmendes94** [AltNyx/youtubetospotify#5]
```
PS C:\Users\Matheus\Documents\YoutubeToSpotify-master> python main.py
Traceback (most recent call last):
  File "C:\Users\Matheus\Documents\YoutubeToSpotify-master\main.py", line 29, in <module>
    main()
  File "C:\Users\Matheus\Documents\YoutubeToSpotify-master\main.py", line 6, in main
    yt = Youtube()
  File "C:\Users\Matheus\Documents\YoutubeToSpotify-master\youtube.py", line 35, in __init__
    self.youtube = build(
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\discovery.py", line 278, in build
    service = build_from_document(
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\discovery.py", line 527, in build_from_document
    credentials = _auth.default_credentials(
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\googleapiclient\_auth.py", line 54, in default_credentials
    credentials, _ = google.auth.default(scopes=scopes, quota_project_id=quota_project_id)
  File "C:\Users\Matheus\AppData\Local\Programs\Python\Python310\lib\site-packages\google\auth\_default.py", line 488, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
PS C:\Users\Matheus\Documents\YoutubeToSpotify-master>

```

**Comment by AnubisXHyperX** [comment]
You need to follow instructions on the GCP console
